/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface GalleryItem {
  'id' : bigint,
  'title' : string,
  'blob' : ExternalBlob,
  'description' : string,
  'timestamp' : bigint,
}
export interface PmSuryaGharApplication {
  'id' : bigint,
  'passportPhoto' : ExternalBlob,
  'status' : string,
  'fullName' : string,
  'submittedBy' : Principal,
  'email' : string,
  'timestamp' : bigint,
  'aadhaarCard' : ExternalBlob,
  'phoneNumber' : string,
  'electricityBill' : ExternalBlob,
  'bankPassbook' : ExternalBlob,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGalleryItem' : ActorMethod<[ExternalBlob, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getApplicationStatus' : ActorMethod<[bigint], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getGallery' : ActorMethod<[], Array<GalleryItem>>,
  'getPmSuryaGharApplicationById' : ActorMethod<
    [bigint],
    PmSuryaGharApplication
  >,
  'getPmSuryaGharApplicationsFiltered' : ActorMethod<
    [string, string],
    Array<PmSuryaGharApplication>
  >,
  'getSitemapXml' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    { 'id' : bigint, 'timestamp' : bigint }
  >,
  'submitPmSuryaGharApplication' : ActorMethod<
    [
      string,
      string,
      string,
      ExternalBlob,
      ExternalBlob,
      ExternalBlob,
      ExternalBlob,
    ],
    { 'id' : bigint, 'status' : string }
  >,
  'updateApplicationStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];